### ISSUE TITLE
Crushing node process on CSV_RECORD_INCONSISTENT_COLUMNS Error

### ISSUE THREAD

**Issue by codersbet** [adaltas/node-csv#338]
Node process is crushing with the following error message even though the entire logic is in a try/catch block
```

node:events:505                                                                                                                                          │
│       throw er; // Unhandled 'error' event                                                                                                               │
│       ^                                                                                                                                                  │
│ CsvError: Invalid Record Length: columns length is 8, got 9 on line 6                                                                                    │
│     at Parser.__onRecord (/app/node_modules/csv-parse/dist/cjs/index.cjs:924:9)                                                                          │
│     at Parser.__parse (/app/node_modules/csv-parse/dist/cjs/index.cjs:879:34)                                                                            │
│     at Parser._flush (/app/node_modules/csv-parse/dist/cjs/index.cjs:621:22)                                                                             │
│     at Parser.final [as _final] (node:internal/streams/transform:111:10)                                                                                 │
│     at callFinal (node:internal/streams/writable:696:12)                                                                                                 │
│     at prefinish (node:internal/streams/writable:708:7)                                                                                                  │
│     at finishMaybe (node:internal/streams/writable:718:5)                                                                                                │
│     at Writable.end (node:internal/streams/writable:632:5)                                                                                               │
│     at ReadStream.onend (node:internal/streams/readable:705:10)                                                                                          │
│     at Object.onceWrapper (node:events:641:28)                                                                                                           │
│ Emitted 'error' event on Parser instance at:                                                                                                             │
│     at Parser.onerror (node:internal/streams/readable:785:14)                                                                                            │
│     at Parser.emit (node:events:527:28)                                                                                                                  │
│     at Parser.emit (node:domain:475:12)                                                                                                                  │
│     at emitErrorNT (node:internal/streams/destroy:151:8)                                                                                                 │
│     at emitErrorCloseNT (node:internal/streams/destroy:116:3)                                                                                            │
│     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {                                                                     │
│   code: 'CSV_RECORD_INCONSISTENT_COLUMNS',

```
A try/catch doesn't prevent the node process from crushing.

**Comment by wdavidw** [comment]
Please respect the bug report template when filling the issue. I will close otherwise.
